yatube/about/urls.py
# файл about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/',
         views.AboutAuthorView.as_view(),
         name='author'),
    path('tech/',
         views.AboutTechView.as_view(),
         name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Отдельная страница групп
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание и редактирование записи
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/',
         views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Заголовок',
        max_length=200,
        help_text='Введите заголовок поста'
    )
    slug = models.SlugField(
        'Адрес страницы группы',
        unique=True
    )
    description = models.TextField(
        'Описание',
        help_text='Введите описание группы'
    )

    class Meta:
        verbose_name = 'Group'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='group_posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='group_posts',
        blank=True, null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.

    class Meta:
        verbose_name = 'Post'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
        blank=False,
        null=False
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментатор'
    )
    text = models.TextField(
        max_length=20000,
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
        blank=False
    )

    class Meta:
        verbose_name = 'Comment'
        ordering = ['pub_date']

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписывающийся'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписант'
    )

    class Meta:
        verbose_name = 'Follow'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='user_author'
            ),
            models.CheckConstraint(
                name='author_author',
                check=~models.Q(user=models.F('author'))
            )
        ]

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Post, Comment

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET, require_http_methods

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Comment, Follow


@require_GET
def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {'page_obj': page_obj}
    return render(request, template, context)


@require_GET
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@require_GET
def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = author.group_posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author).exists()
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    count = post.author.group_posts.count()
    comments = Comment.objects.filter(post=post_id)
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'count': count,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
@require_http_methods(["GET", "POST"])
def post_create(request):
    groups = Group.objects.all()
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author.username)
    template = 'posts/create_post.html'
    return render(request, template, {'form': form, 'groups': groups})


@login_required
@require_http_methods(["GET", "POST"])
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        template = 'posts:post_detail'
        form.save()
        return redirect(template, post_id=post.pk)
    groups = Group.objects.all()
    template = 'posts/create_post.html'
    context = {
        'form': form,
        'groups': groups,
        'post': post,
        'is_edit': is_edit
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    template = 'posts:post_detail'
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect(template, post_id=post_id)


@login_required
def follow_index(request):
    post_set = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_set, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user, author=author)
    follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
Новый пост
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}                     
              </div>
              <div class="card-body">    
                
                {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}
                
                <form method="post" enctype="multipart/form-data" href="{% url 'posts:post_create' %}">
                  {% csrf_token %}
                  {{form.image}}

                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      {% for group in groups %}
                        <option value="{{ group.pk }}"selected>{{ group.title }} </option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
Это страница подписок
{% endblock %}
{% block content %}
{% load thumbnail %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
  <h1>Избранные авторы</h1>
  <article>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author }}
      </li>
      <a href="{% url "posts:profile" username=post.author%}">все посты пользователя</a>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p><a href="{% url "posts:post_detail" post.pk %}">подробная информация </a></p>
    {% if post.group %} <a href="{% url "posts:group_list" post.group.slug %}">все записи группы</a> {{post.group.title}}
    {% endif %}
    {% if not forloop.last %}<hr>
    {% endif %}
    
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  <!-- под последним постом нет линии -->
</article>
</div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
{{group.title}}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  Записи сообщества <h1>{{ group.title }}</h1>
    <p> {{ group.description }}</p>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% if not forloop.last %}<hr>
    {% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
</div>  
{% endblock %}    

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Это главная страница проекта Yatube
{% endblock %}
{% block content %}
{% load thumbnail %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  {% include 'posts/includes/switcher.html' %}
  <article>
    {% load cache %}
    {% cache 20 index_page page_obj.number %}
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author }}
      </li>
      <a href="{% url "posts:profile" username=post.author%}">все посты пользователя</a>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p><a href="{% url "posts:post_detail" post.pk %}">подробная информация </a></p>
    {% if post.group %} <a href="{% url "posts:group_list" post.group.slug %}">все записи группы</a> {{post.group.title}}
    {% endif %}
    {% if not forloop.last %}<hr>
    {% endif %}
    
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
    {% endcache %}  
  <!-- под последним постом нет линии -->
</article>
</div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Пост
{{post.text|truncatechars:30}}
{% endblock %}
{% block content %}
{% load thumbnail %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->   
                {% if post.group %}
                <li class="list-group-item">
                  Группа: {{post.group.title}}
                
                <p><a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы </a></p>        
                {% endif %}
                </li>
              <li class="list-group-item">
                Автор: {{ post.author }} 
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ count }}</span>
              </li>
              <li class="list-group-item">
              <p><a href="{% url "posts:profile" username=post.author%}">все посты пользователя</a></p> 
              </li> 
          </ul>
        </aside>
        
      </div>
        <li class="list-group-item">
          {{post.text}}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        
    <a class="btn btn-primary" href={% url 'posts:post_edit' post_id=post.pk%}>
      редактировать запись
    </a>
{% include 'posts/includes/add_comment.html' %}
        </li>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Профайл пользователя {{author}}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ author }} </h1>
    <h3>Всего постов: {{ posts.count }} </h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}  
      <article>
      {% for post in page_obj %}
        <ul>
          <li>
          Автор: {{ post.author }}
          </li>
          <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          </ul>
          <p>{{ post.text|truncatewords:10 }}</p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <a href="{% url "posts:post_detail" post.pk %}">подробная информация </a>
          <!-- Остальные посты. после последнего нет черты -->
          {% if post.group %}
            <p><a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы </a></p>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
        <!-- Здесь подключён паджинатор -->  
      {% include 'posts/includes/paginator.html' %}
      </article>  
</div>
{% endblock %}

yatube/templates/posts/update_post.html
{% extends 'base.html' %}
{% block title %}
Редактировать пост
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data" href="{% url 'posts:post_edit' %}">
                  {% csrf_token %}                        
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" >---------</option>
                      {% for group in groups %}
                        <option value="{{ group.pk }}">{{ group.title }} </option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% include 'posts/includes/paginator.html' %}
{% endblock %}